name: olof_queueing
description: "OLOF Queueing System - Our Lady of Fatima Eye Ear Nose Throat Center"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Routing
  go_router: ^15.1.2

  # State Management
  provider: ^6.1.4

  # Backend
  supabase_flutter: ^2.9.0
  storage_client: ^2.8.0

  # QR Code
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.0.2

  # Camera & Image
  image_picker: ^1.1.2

  # Fonts
  google_fonts: ^6.2.1

  # Audio
  audioplayers: ^6.4.0

  # Color picker for Clinical Drawings
  flutter_colorpicker: ^1.1.0

  # File and Path Utilities
  path_provider: ^2.1.2

  # Utilities
  uuid: ^4.5.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/sounds/
    - assets/diagrams/
